const $ = s => document.querySelector(s);
const esc = x => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone = x => JSON.parse(JSON.stringify(x));
const operationKey = () => [...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,'0')).join('');
const S = {csrf:'', page:'home', project:null, projects:[], assets:[], tasks:[], budgets:[], settings:{}, pending:new Map()};
const kinds = {concepts:'故事提案',script:'结构化剧本',bible:'角色与世界',storyboard:'分镜草案',image:'生成图片',video:'生成视频',tts:'生成配音',animatic:'完整预演',render:'正式合成'};
const states = {queued:'等待执行',dispatching:'正在提交',submitted:'远端处理中',running:'处理中',succeeded:'已生成候选',failed:'失败',reconciling:'待核对 · 不重复提交',cancelled:'已取消'};
const motionNames = {none:'设计静帧',camera:'镜头运动',subject_action:'人物动作',lip_sync:'口型同步'};
function toast(text, error=false){const t=$('#toast');t.textContent=text;t.className=error?'error':'';t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,error?16000:6000);}
async function api(path,options={}){
 const ctl=new AbortController(), timer=setTimeout(()=>ctl.abort(),120000);
 const method=options.method||'GET', headers={'X-CSRF-Token':S.csrf,...options.headers};
 if(options.body && !(options.body instanceof FormData)){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body);}
 const signature=method+path+(typeof options.body==='string'?options.body:'');
 if(method==='POST' && path.endsWith('/tasks')){if(!S.pending.has(signature))S.pending.set(signature,operationKey());headers['Idempotency-Key']=S.pending.get(signature);}
 try{const r=await fetch('/api/v1'+path,{...options,method,headers,signal:ctl.signal});
  if(!r.ok){let e;try{e=await r.json();}catch{e={};}throw new Error(e.error?.message || (Array.isArray(e.detail)?e.detail.map(x=>x.msg).join('\n'):e.detail) || `HTTP ${r.status}`);}
  S.pending.delete(signature);return options.blob?await r.blob():await r.json();
 }catch(e){if(e.name==='AbortError')throw new Error('请求响应超时。请先检查任务列表；再次点击相同请求会复用幂等编号。');throw e;}finally{clearTimeout(timer);}
}
const base=()=>`/projects/${S.project.id}`;
const mediaURL=a=>`/api/v1${base()}/assets/${a.id}/file`;
const outputURL=(t,name)=>`/api/v1${base()}/tasks/${t.id}/files/${name}`;
function badge(text,style=''){return `<span class="badge ${style}">${esc(text)}</span>`;}
function button(text,act,cls='',extra=''){return `<button class="${cls}" data-act="${act}" ${extra}>${text}</button>`;}
function metric(name,value,sub=''){return `<div class="metric"><span>${name}</span><strong>${value}</strong><small>${sub}</small></div>`;}
function heading(eyebrow,title,subtitle,actions=''){return `<div class="heading"><div><div class="eyebrow">${eyebrow}</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="actions">${actions}</div></div>`;}
function empty(title,description,action=''){return `<div class="empty"><div class="symbol">◇</div><h2>${esc(title)}</h2><p>${esc(description)}</p>${action}</div>`;}
function field(name,title,value='',type='text',extra=''){return `<label>${title}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function area(name,title,value='',extra=''){return `<label>${title}<textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`;}
function select(name,title,options,value){return `<label>${title}<select name="${name}">${options.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;}
function money(n){return (Number(n||0)/1000000).toFixed(4);}
function micros(s){if(!/^\d+(\.\d{1,6})?$/.test(String(s)))throw new Error('金额最多保留六位小数');const [a,b='']=String(s).split('.');return Number(a)*1000000+Number(b.padEnd(6,'0'));}
function currentGate(g){return S.project?.approvals.some(a=>a.gate===g&&a.current);}
function loginScreen(){
 $('#app').innerHTML=`<main class="login"><section class="login-art"><div class="brand"><div class="brand-mark">MJ</div><div>漫境<small>ORIGINAL DRAMA STUDIO</small></div></div><h1>让一个故事，<br>成为两分钟的世界。</h1><p>从剧本、角色到镜头与声音。每一步可以审阅，每个镜头可以重做，每次创作都有迹可循。</p></section><section class="login-form"><form data-form="login"><div class="eyebrow">YOUR PRIVATE WORKSPACE</div><h2>进入创作工作台</h2><p>使用本机 .env 中的管理员密码登录。</p>${field('password','管理员密码','','password','required autocomplete="current-password"')}${button('登录工作台 →','','primary','type="submit"')}<div class="login-note">首次启动：<code>python -m mj.cli init</code><br>系统生成随机密码，不提供公共默认账号密码。<br>没有配置外部服务时，仍可使用离线工程预演。</div></form></section></main>`;
}
async function loadProject(id){S.project=await api('/projects/'+id);[S.assets,S.tasks,S.budgets]=await Promise.all([api(base()+'/assets'),api(base()+'/tasks'),api(base()+'/budgets')]);}
async function refresh(){if(S.project)await loadProject(S.project.id);S.projects=await api('/projects');render();}
function render(){
 const nav=[['home','全部项目'],...(S.project?[['overview','制作总览'],['story','策划与剧本'],['bible','角色与世界'],['shots','分镜工作台'],['assets','素材与选片'],['render','声音与合成'],['tasks','生成任务'],['history','版本历史']]:[]),['settings','模型与预算']];
 $('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">MJ</div><div>漫境<small>ORIGINAL DRAMA STUDIO</small></div></div><div class="nav-label">WORKSPACE / 创作空间</div><nav class="nav">${nav.map(([id,text],i)=>button(`<span class="num">${String(i+1).padStart(2,'0')}</span>${text}`,'nav',S.page===id?'active':'',`data-page="${id}"`)).join('')}</nav><div class="sidebar-footer"><span class="dot"></span>本地可控 · 版本留存<br>MJ STUDIO / 0.3.0<br>生成候选 ≠ 审核通过</div></aside><main class="main"><header class="topbar"><div class="crumb">工作空间 / ${esc(S.project?.title||'所有原创项目')}</div><div class="top-right">${badge(S.settings.mode==='production'?'生产工作区':'离线工程模式',S.settings.mode==='production'?'good':'warn')}${button('退出','logout','ghost small')}</div></header><div class="content">${pageContent()}</div></main></div>`;
 if(S.page==='history')loadHistory();
}
function pageContent(){
 const p=S.project,c=p?.content;
 if(S.page==='home')return home();
 if(S.page==='settings')return settingsPage();
 if(!p)return empty('先创建一个原创项目','项目会保存故事、分镜、资产版本与任务记录。',button('创建项目','new-project','primary'));
 const mockBanner=S.settings.mode!=='production'?'<div class="banner"><span>◇</span><div><strong>离线工程模式</strong>　模拟文本、图片、视频和测试音频均明确标注 MOCK，不会发起付费调用，也不能通过真实成片验收。</div></div>':'';
 const views={overview:overview,story:story,bible:bible,shots:shots,assets:assets,render:renderPage,tasks:tasksPage,history:()=>heading('VERSION HISTORY','每一次修改，都可以回看','恢复会创建新版本，不覆盖历史。')+'<div id="history-list" class="loading">读取历史…</div>'};
 return mockBanner+(views[S.page]?.()||overview());
}
function home(){return heading('MAKE STORIES, NOT JUST CLIPS','你的原创漫剧工作空间','从一个想法开始。先确定故事与角色，再用分镜、配音和样片验证它。',button('新建原创项目 ＋','new-project','primary'))+`<div class="grid four">${metric('原创项目',S.projects.length,'仅展示真实保存的项目')}${metric('目标成片','120 s','可修改画幅、帧率与时长')}${metric('审核关卡','4','故事 → 预演 → 样片 → 交付')}${metric('费用控制',S.settings.external_enabled?'已启用':'未开启','未经授权不调用外部生成')}</div><div class="panel-title section-gap"><h2>最近项目</h2>${button('创建离线演示','demo-project','ghost')}</div>`+(S.projects.length?`<div class="grid three">${S.projects.map((p,i)=>`<button class="project-card" data-act="open-project" data-id="${p.id}"><div class="project-cover"><strong>${String(i+1).padStart(2,'0')}</strong>${badge(`${p.spec.width} × ${p.spec.height}`)}</div><div class="project-info"><h3>${esc(p.title)}</h3><p>${esc(p.brief.slice(0,80))}</p><div class="row">${badge(`${p.spec.total_frames/p.spec.fps} 秒`)}${badge(`版本 ${p.revision}`)}</div></div></button>`).join('')}</div>`:empty('故事还没有开始','创建你的第一个项目，或者加载一个明确标注的离线工程演示。',button('创建项目','new-project','primary')));}
function overview(){const p=S.project,c=p.content,frames=c.shots.reduce((n,s)=>n+s.frames,0);return heading('PRODUCTION OVERVIEW',p.title,p.brief,button('刷新状态','refresh','ghost')+button('开始策划 →','nav','primary','data-page="story"'))+`<div class="grid four">${metric('当前版本','v'+p.revision,'所有改动均保存历史')}${metric('分镜',c.shots.length,`${frames} / ${p.spec.total_frames} 帧`)}${metric('已审核素材',S.assets.filter(a=>a.review==='accepted').length,`共有 ${S.assets.length} 个候选`)}${metric('处理中',S.tasks.filter(t=>!['succeeded','failed','cancelled'].includes(t.state)).length,'任务持久化，可核对')}</div><section class="panel section-gap"><div class="panel-title"><h2>制作关卡</h2>${badge('审批绑定具体版本','purple')}</div><div class="steps">${[['G1','故事与剧本','主角目标、冲突、可见行动与结尾。'],['G2','资产与预演','确定角色参考、分镜与完整节奏。'],['G3','真实动作样片','10–20 秒相邻镜头，检查动作和声音。'],['G4','成片交付','完整看完，核对字幕、声音和连续性。']].map(([g,title,desc])=>`<div class="step">${badge(g,currentGate(g)?'good':'')}<strong>${title}</strong><p>${desc}</p>${button(currentGate(g)?'已批准 · 查看':'提交人工确认','approve','small',`data-gate="${g}"`)}</div>`).join('')}</div></section><div class="grid two"><section class="panel"><h2>制作规格</h2><div class="stack"><div class="row">${badge(`${p.spec.width} × ${p.spec.height}`)}${badge(`${p.spec.fps} fps`)}${badge('48 kHz 音频')}</div><p class="small">${esc(p.style)}</p><p class="small">正式输出由实际视频帧数与音频采样数验证，不会粗暴裁掉结尾凑时长。</p></div></section><section class="panel"><h2>下一步</h2><p class="small">${!c.concepts.length?'先生成或手写至少三个故事方向，选择一个继续。':!c.script.length?'写下可见行动和旁白对白，保存剧本并确认 G1。':!c.shots.length?'建立角色和世界设定，然后拆分为镜头。':'审阅分镜和声音，先做完整预演，再选择相邻镜头制作真实样片。'}</p>${button('进入分镜工作台','nav','ghost','data-page="shots"')}</section></div>`;}
function story(){const c=S.project.content;return heading('STORY ROOM','先让故事成立','对比不同视角与冲突，再把故事写成能够拍出来的行动。',button('生成三种方案','generate','', 'data-kind="concepts"')+button('生成剧本','generate','primary','data-kind="script"'))+`<form data-form="story"><section class="panel"><div class="panel-title"><h2>故事方向</h2>${button('手写一个方案','add-concept','ghost small','type="button"')}</div>${c.concepts.length?`<div class="grid three">${c.concepts.map((x,i)=>`<article class="concept ${c.selected_concept===x.id?'selected':''}"><div class="concept-top">${badge('方向 '+(i+1),'purple')}<label><input type="radio" name="selected" value="${esc(x.id)}" ${c.selected_concept===x.id?'checked':''}>采用</label></div><div class="stack">${field(`title_${i}`,'标题',x.title)}${area(`logline_${i}`,'一句话故事',x.logline)}${area(`conflict_${i}`,'核心冲突',x.conflict)}${area(`ending_${i}`,'结尾',x.ending)}</div></article>`).join('')}</div>`:'<p class="small">还没有方案。可以手写，也可以通过已配置的模型生成；模拟模式仅提供结构模板。</p>'}</section><section class="panel"><div class="panel-title"><h2>剧本与节拍</h2>${button('新增节拍 ＋','add-beat','ghost small','type="button"')}</div>${c.script.map((b,i)=>`<div class="beat"><div class="beat-id">${esc(b.id)}</div>${area(`action_${i}`,'画面中发生的动作',b.action)}${area(`narration_${i}`,'旁白 / 台词',b.narration)}<div></div>${field(`speaker_${i}`,'声音归属 ID',b.speaker_id)}${field(`emotion_${i}`,'情绪与语气',b.emotion)}</div>`).join('')||'<p class="small">动作、情绪和声音分开写。生成结果先留在任务列表，审阅后再应用。</p>'}</section><div class="actions">${button('确认 G1','approve','','type="button" data-gate="G1"')}${button('保存新版本','','primary','type="submit"')}</div></form>`;}
function bible(){const b=S.project.content.bible;return heading('CHARACTER & WORLD','给故事一个稳定的世界','角色、服装、场景与道具都有固定 ID。参考图片从素材库导入并审核。',button('生成定妆/场景图','generate','','data-kind="image"')+button('生成设定草案','generate','primary','data-kind="bible"'))+`<form data-form="bible"><div class="grid three">${[['characters','角色','C'],['scenes','场景','SC'],['props','道具','P']].map(([k,title,prefix])=>`<section class="panel"><div class="panel-title"><h2>${title}</h2>${button('＋','add-entity','ghost',`type="button" data-key="${k}" data-prefix="${prefix}"`)}</div><div class="stack">${b[k].map((x,i)=>`<div class="concept"><div class="row">${badge(x.id,'purple')}</div><div class="stack section-gap">${field(`${k}_name_${i}`,'名称',x.name)}${area(`${k}_description_${i}`,'外观 / 空间 / 状态约束',x.description)}${field(`${k}_refs_${i}`,'参考素材 ID（逗号分隔）',x.reference_ids.join(','))}</div></div>`).join('')||'<p class="small">尚未添加。先建立必要设定，不强制生成不需要的资产。</p>'}</div></section>`).join('')}</div><div class="actions">${button('保存世界设定','','primary','type="submit"')}</div></form>`;}
function visual(asset){if(!asset)return '<span class="placeholder">◇</span>';const url=mediaURL(asset);if(asset.kind==='image')return `<img src="${url}" alt="${esc(asset.name)}" loading="lazy">`;if(asset.kind==='video')return `<video src="${url}" controls preload="metadata"></video>`;return `<audio src="${url}" controls preload="metadata"></audio>`;}
function shots(){const p=S.project,c=p.content;return heading('STORYBOARD','逐镜头，搭建你的故事','先审分镜和节奏，再生成昂贵的视频。人物动作不能被静图推拉替代。',button('拆分分镜','generate','','data-kind="storyboard"')+button('新增镜头 ＋','edit-shot','primary'))+`<div class="toolbar"><div class="row">${badge(`${c.shots.length} 个镜头`)}${badge(`${c.shots.reduce((n,s)=>n+s.frames,0)} / ${p.spec.total_frames} 帧`,c.shots.reduce((n,s)=>n+s.frames,0)===p.spec.total_frames?'good':'warn')}</div><div class="row">${button('均分目标时长','distribute','ghost small')}${button('完整预演','generate','small','data-kind="animatic"')}${button('高级 JSON 编辑','json-editor','ghost small')}</div></div>`+(c.shots.length?`<div class="grid three">${c.shots.map((s,i)=>`<article class="shot-card"><div class="shot-visual">${visual(S.assets.find(a=>a.id===s.video_asset))}</div><div class="shot-body"><div class="row">${badge(s.id,'purple')}<span class="small muted">${(s.frames/p.spec.fps).toFixed(2)} s · ${esc(s.framing)}</span></div><p>${esc(s.action)}</p><div class="row">${badge(motionNames[s.motion])}${badge(s.audio_asset?'已选音轨':'待配音',s.audio_asset?'good':'')}</div><div class="row">${button('编辑','edit-shot','',`data-id="${s.id}"`)}${button('生图','generate','',`data-kind="image" data-id="${s.id}"`)}${button('视频','generate','',`data-kind="video" data-id="${s.id}"`)}${button('配音','generate','',`data-kind="tts" data-id="${s.id}"`)}</div></div></article>`).join('')}</div>`:empty('还没有分镜','先建立剧本和世界设定，或者手动添加镜头。',button('添加第一个镜头','edit-shot','primary')));}
function assets(){return heading('ASSET LIBRARY','素材、候选与参考','每个文件按内容哈希保存。先审核，再选择；替换候选不会删除原素材。',button('上传素材 ＋','upload','primary'))+(S.assets.length?`<div class="grid three">${S.assets.map(a=>`<article class="asset-card"><div class="asset-preview">${visual(a)}</div><div class="asset-meta"><h3>${esc(a.name)}</h3><div class="row">${badge(a.kind)}${badge(a.mock?'MOCK / 工程素材':'真实素材',a.mock?'warn':'')}${badge(a.review==='accepted'?'已审核':a.review==='rejected'?'已驳回':'待审核',a.review==='accepted'?'good':'')}</div><small class="mono">${a.id}</small><small>${a.info.duration?Number(a.info.duration).toFixed(2)+' 秒 · ':''}${esc(motionNames[a.motion])}</small><div class="row">${button('审核','review','',`data-id="${a.id}"`)}${button('关联到镜头','select-asset','',`data-id="${a.id}"`)}</div></div></article>`).join('')}</div>`:empty('把画面与声音放进来','支持常见图片、视频和音频。需要记录素材的来源和使用权限。',button('上传第一份素材','upload','primary')));}
function tasksPage(){return heading('GENERATION QUEUE','让每一次生成有迹可循','页面自动刷新任务状态。未知提交先核对，不盲目重发；实际费用不会自动假设为零。',button('刷新','refresh','ghost'))+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>供应商</th><th>费用状态</th><th>操作</th></tr></thead><tbody>${S.tasks.map(t=>`<tr><td><div class="task-name">${kinds[t.kind]||esc(t.kind)}</div><small class="mono">${t.id.slice(0,10)} · v${t.revision}</small>${t.error?`<p class="error-text">${esc(t.error)}</p>`:''}</td><td>${badge(states[t.state]||t.state,t.state==='succeeded'?'good':t.state==='reconciling'?'warn':'')}${t.cancel_requested?'<p>已请求取消，远端可能仍在运行</p>':''}</td><td>${esc(t.provider)}${t.remote_request_id?`<p class="mono">${esc(t.remote_request_id)}</p>`:''}</td><td>${esc(t.fee_state)}<p>${t.cap_micros?'预占 '+money(t.cap_micros):'本地 / 无外部账单'}</p></td><td>${t.state==='succeeded'&&['concepts','script','bible','storyboard'].includes(t.kind)?button('审阅 / 应用','inspect-result','',`data-id="${t.id}"`):''}${['queued','running','dispatching','submitted','reconciling'].includes(t.state)?button('请求取消','cancel-task','',`data-id="${t.id}"`):''}${t.state==='reconciling'?button('查原任务','reconcile','',`data-id="${t.id}"`):''}${t.budget_id&&['uncertain','reserved'].includes(t.fee_state)&&['succeeded','failed','reconciling','cancelled'].includes(t.state)?button('登记账单','settle','',`data-id="${t.id}"`):''}</td></tr>`).join('')||'<tr><td colspan="5">没有任务。先去策划、分镜或合成页面发起。</td></tr>'}</tbody></table></div></section>`;}
function renderPage(){const p=S.project,c=p.content,outputs=S.tasks.filter(t=>t.state==='succeeded'&&t.result?.qa);let offset=0;return heading('TIMELINE & SOUND','把画面与声音，放在同一条时间线上','旁白、音乐和音效分别混音。无声音轨的视频也能使用；过长的台词会阻止正式渲染。',button('完整预演','generate','','data-kind="animatic"')+button('创建合成任务','generate','primary','data-kind="render"'))+`<div class="grid four">${metric('目标时长',p.spec.total_frames/p.spec.fps+' s',p.spec.total_frames+' 个视频帧')}${metric('当前镜头时长',(c.shots.reduce((n,s)=>n+s.frames,0)/p.spec.fps).toFixed(2)+' s','整数帧时间基准')}${metric('独立声音轨',c.extra_audio.length,'旁白与视觉切点互不绑定')}${metric('成功输出',outputs.length,'仅计算实际完成的渲染')}</div><section class="panel section-gap"><div class="panel-title"><h2>基础时间线</h2>${button('添加声音轨','audio-track','ghost small')}</div><div class="timeline">${c.shots.map(s=>`<span title="${esc(s.id)}">${esc(s.id)}</span>`).join('')}</div><div class="table-wrap"><table><thead><tr><th>镜头</th><th>帧区间</th><th>动作</th><th>音频</th><th>顺序</th></tr></thead><tbody>${c.shots.map((s,i)=>{const start=offset;offset+=s.frames;return `<tr><td>${esc(s.id)}</td><td class="mono">${start}–${offset}</td><td>${esc(s.action.slice(0,50))}</td><td>${s.audio_asset?'已选':'未选'}</td><td>${button('↑','move-shot','','data-index="'+i+'" data-direction="-1"')}${button('↓','move-shot','','data-index="'+i+'" data-direction="1"')}${button('编辑','edit-shot','','data-id="'+s.id+'"')}</td></tr>`;}).join('')}</tbody></table></div></section><form class="panel" data-form="subtitle"><h2>字幕与混音</h2><div class="field-row three">${field('font_size','字幕字号（画布像素）',c.subtitles.font_size,'number','min="16" max="120"')}${field('margin_v','距底部（像素）',c.subtitles.margin_v,'number','min="0" max="1000"')}${field('line_chars','每条字幕字数',c.subtitles.line_chars,'number','min="4" max="32"')}</div><div class="row section-gap"><label><input type="checkbox" name="duck" ${c.duck_music?'checked':''}>说话时压低背景音乐</label>${button('保存声音设置','','primary','type="submit"')}</div><p class="small section-gap">字幕按实际语音长度分配句段时间，尚未提供逐字强制对齐；终审时需要检查断句与时间。</p></form><div class="grid two">${outputs.map(t=>`<section class="panel"><div class="panel-title"><h2>${t.result.mock?'工程预演':'候选成片'}</h2>${badge(t.result.mock?'MOCK':'待人工终审',t.result.mock?'warn':'purple')}</div><video class="video-output" src="${outputURL(t,'final_subtitled.mp4')}" controls preload="metadata"></video><div class="row section-gap">${badge(t.result.qa.frames+' 帧','good')}${badge(t.result.qa.samples+' 采样')}${badge(t.result.qa.duration_seconds+' 秒')}</div><div class="row section-gap"><a href="${outputURL(t,'final_clean.mp4')}" download>干净版</a><a href="${outputURL(t,'captions.srt')}" download>字幕</a><a href="${outputURL(t,'qa.json')}" download>质检记录</a>${button('导出项目包','export','small',`data-id="${t.id}"`)}</div></section>`).join('')}</div>`;}
function settingsPage(){return heading('CAPABILITIES & BUDGET','模型与费用，由你掌控','密钥只通过服务器环境变量注入；不会存入浏览器，也不会出现在项目导出包中。')+`<div class="banner ${S.settings.external_enabled?'':'warn'}">${S.settings.external_enabled?'外部调用开关已打开；每次调用仍需有效预算与对应审批。':'外部调用默认关闭。离线模式可以完整测试编辑、素材和合成流程。'}</div><div class="banner">ComfyUI 自托管通道：${S.settings.comfyui_enabled?'已启用（仍需 G1 与逐任务外发授权）':'未启用'}。GPU 费用未计量，不等于计算免费；不使用云 API 预算代替服务器资源授权。</div><section class="panel"><h2>可用供应商</h2><div class="table-wrap"><table><thead><tr><th>名称</th><th>类型</th><th>凭据状态</th><th>模型效果</th></tr></thead><tbody><tr><td>mock</td><td>本地工程模拟</td><td>不需要密钥</td><td>不能作为真实漫剧验收</td></tr>${(S.settings.providers||[]).map(p=>`<tr><td>${esc(p.id)}</td><td>${esc(p.type)}${p.type==='comfyui'?button('检查节点/模型','comfy-check','small',`data-provider="${esc(p.id)}"`):''}</td><td>${p.type==='comfyui'&&!p.auth_required?'私网访问（须隔离）':p.key_present?'环境变量已配置':'未配置'}</td><td>需实际样片验证</td></tr>`).join('')}</tbody></table></div><p class="small section-gap">在服务器设置 <code>MJ_PROVIDERS_FILE</code>，参考仓库的 <code>providers.example.json</code>。生产模式使用 PostgreSQL；不能在离线模式偷偷启用外部消费。</p></section>`+(S.project?`<section class="panel"><div class="panel-title"><h2>本项目预算授权</h2>${button('新建预算授权','budget','primary small')}</div>${S.budgets.map(b=>`<div class="toolbar"><div>${badge(b.currency)} <strong>${money(b.used_micros)} / ${money(b.limit_micros)}</strong><p class="small">${esc(b.id)} · 单次上限 ${money(b.per_task_micros)} · ${b.revoked?'已撤销':'授权到 '+new Date(b.expires*1000).toLocaleString()}</p></div>${button('撤销后续使用','revoke','small',`data-id="${b.id}"`)}</div>`).join('')||'<p class="small">尚无预算。生成收费任务前需要明确金额、供应商、任务类型与参考素材外发范围。</p>'}</section>`:'');}
async function saveContent(content){S.project=await api(base()+'/workspace',{method:'PUT',body:{expected_revision:S.project.revision,content}});render();toast('已保存为版本 v'+S.project.revision);}
function modal(title,body,form,extra=''){const d=$('#modal');d.innerHTML=`<form data-form="${form}" ${extra}><div class="dialog-head"><h2 id="modal-title">${esc(title)}</h2>${button('×','close','ghost','type="button" aria-label="关闭"')}</div>${body}<footer>${button('取消','close','','type="button"')}${button('确认','','primary','type="submit"')}</footer></form>`;d.showModal();}
function close(){if($('#modal').open)$('#modal').close();}
function genDialog(kind,id=''){const providers=[['mock','本地 MOCK · 不产生费用'],...(S.settings.providers||[]).filter(p=>p.type==='comfyui'?kind==='image':p.type==='fal_queue'?kind==='video':['concepts','script','bible','storyboard','image','tts'].includes(kind)).map(p=>[p.id,p.id])];const local=['animatic','render'].includes(kind);const shots=S.project.content.shots;modal(kinds[kind],`${local?'':select('provider','供应商',providers,'mock')}${id?field('shot_id','镜头 ID',id,'text','readonly'):['video','tts'].includes(kind)?select('shot_id','镜头',shots.map(s=>[s.id,s.id+' · '+s.action.slice(0,25)]),shots[0]?.id):''}${local?'':area('prompt','补充方向（可留空）','')}${kind==='image'?'<div id="comfy-options"></div>':''}${local?'':select('budget_id','预算授权',[['','无 / 仅模拟'],...S.budgets.filter(b=>!b.revoked).map(b=>[b.id,b.currency+' · 剩余 '+money(b.limit_micros-b.used_micros)])],'')}${local?'':field('cap','本次预占金额（同预算币种）','0','text')}${kind==='tts'?field('voice','声音 ID','alloy'):''}${['video','render','animatic'].includes(kind)?`<label><input name="sample" type="checkbox">代表性样片（视频任务用于 G3 前试作；合成取相邻镜头）</label>${field('sample_ids','样片镜头 ID（例如 SH01,SH02,SH03）','')}`:''}${!local?'<label><input name="dry" type="checkbox">仅预检（不生成、不花费）</label>':''}<p class="small">${local?'只读取冻结的素材版本，由 Worker 执行。正式合成要求所有画面与声音已审核。':'提交后先生成候选，不会覆盖当前剧本或自动选中素材。外部任务需要预算与阶段授权。'}</p>`,'generate',`data-kind="${kind}" data-shot="${esc(id)}"`);}
async function loadHistory(){const rows=await api(base()+'/history');if(S.page!=='history')return;$('#history-list').className='panel';$('#history-list').innerHTML=`<table><thead><tr><th>版本</th><th>保存时间</th><th>内容指纹</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td>v${r.number}</td><td>${new Date(r.created_at*1000).toLocaleString()}</td><td class="mono">${r.content_hash.slice(0,16)}</td><td>${button('恢复为新版本','restore','',`data-number="${r.number}"`)}</td></tr>`).join('')}</tbody></table>`;}
async function action(el){const a=el.dataset.act,id=el.dataset.id,c=S.project?clone(S.project.content):null;
 if(a==='comfy-check'){const r=await api('/providers/'+encodeURIComponent(el.dataset.provider)+'/check',{method:'POST'});toast(JSON.stringify(r,null,2),!r.ok);return;}if(a==='close'){close();return;}if(a==='nav'){S.page=el.dataset.page;render();return;}if(a==='refresh'){await refresh();return;}
 if(a==='logout'){await api('/logout',{method:'POST'});S.csrf='';S.project=null;loginScreen();return;}
 if(a==='new-project'){modal('开始一个原创项目',field('title','项目名称','','text','required maxlength="120"')+area('brief','故事构想 / 原创文本','','required')+field('style','画风与基调','二维漫画，暖色光影')+`<div class="field-row three">${field('duration','时长（秒）',120,'number','min="10" max="300"')}${select('aspect','画幅',[['portrait','9:16 竖屏'],['landscape','16:9 横屏']],'portrait')}${select('size','输出大小',[['standard','1080p'],['preview','360p 工程测试']],'standard')}</div>`,'project');return;}
 if(a==='open-project'){await loadProject(id);S.page='overview';render();return;}
 if(a==='generate'){genDialog(el.dataset.kind,id);return;}
 if(a==='add-concept'){c.concepts.push({id:'CPT'+Date.now(),title:'新方案',logline:'请填写故事',conflict:'请填写冲突',ending:'请填写结尾'});await saveContent(c);return;}
 if(a==='add-beat'){c.script.push({id:'B'+Date.now(),action:'请填写可见行动',narration:'',speaker_id:'narrator',emotion:'自然'});await saveContent(c);return;}
 if(a==='add-entity'){c.bible[el.dataset.key].push({id:el.dataset.prefix+Date.now(),name:'新设定',description:'请填写稳定的锚点与状态',reference_ids:[]});await saveContent(c);return;}
 if(a==='json-editor'){modal('高级工作区编辑 · 保存将创建新版本',area('json','完整结构（未知字段会被拒绝）',JSON.stringify(c,null,2),'class="json-editor"'),'json');return;}
 if(a==='edit-shot'){const s=c.shots.find(s=>s.id===id)||{id:'SH'+String(c.shots.length+1).padStart(2,'0'),frames:180,action:'',framing:'中景',motion:'subject_action',before:'',after:'',narration:'',character_ids:[],scene_id:c.bible.scenes[0]?.id||'',beat_id:c.script[0]?.id||'',reference_ids:[],source_in_frames:0,fit:'contain'};modal(id?'编辑 '+id:'新增镜头',`<div class="field-row three">${field('id','镜头 ID',s.id,'text','required')}${field('frames','长度（帧）',s.frames,'number','min="1" required')}${field('framing','景别',s.framing)}</div><div class="field-row">${select('scene_id','所属场景',[['','未指定'],...c.bible.scenes.map(e=>[e.id,e.name])],s.scene_id)}${select('beat_id','所属节拍',[['','未指定'],...c.script.map(e=>[e.id,e.id+' · '+e.action.slice(0,25)])],s.beat_id)}</div>${field('characters','出镜角色 ID（逗号分隔）',s.character_ids.join(','))}${area('action','必须可见的动作',s.action,'required')}${select('motion','运动要求',Object.entries(motionNames),s.motion)}<div class="field-row">${area('before','进入镜头时的状态',s.before)}${area('after','结束后的状态',s.after)}</div>${area('narration','此镜头的旁白 / 台词',s.narration)}${field('refs','参考图片素材 ID（逗号分隔）',s.reference_ids.join(','))}<div class="field-row">${field('source_in_frames','源视频入点（按项目帧率）',s.source_in_frames,'number','min="0"')}${select('fit','构图适配',[['contain','完整保留 / 留边'],['cover','铺满画布 / 裁切'] ],s.fit)}</div>`,'shot',`data-original="${esc(id||'')}"`);return;}
 if(a==='distribute'){if(!c.shots.length)throw new Error('先添加分镜');if(!confirm('将镜头均分为目标时长，原节奏会改变。继续？'))return;const total=S.project.spec.total_frames,n=c.shots.length;c.shots.forEach((s,i)=>s.frames=Math.floor(total/n)+(i<total%n?1:0));await saveContent(c);return;}
 if(a==='move-shot'){const i=+el.dataset.index,j=i+(+el.dataset.direction);if(j<0||j>=c.shots.length)return;[c.shots[i],c.shots[j]]=[c.shots[j],c.shots[i]];await saveContent(c);return;}
 if(a==='upload'){modal('导入素材',field('file','图片 / 视频 / 音频','','file','required accept=".png,.jpg,.jpeg,.webp,.mp4,.mov,.mkv,.webm,.mp3,.wav,.m4a"')+area('rights','来源与使用权限','','required'),'upload');return;}
 if(a==='review'){const x=S.assets.find(x=>x.id===id);modal('审核素材 · '+x.name,`<p class="small">${x.mock?'这是工程模拟素材，不能被认定为真实模型生成。':'请观看完整片段，确认动作起止、人物与道具状态。'}</p>${select('status','结论',[['accepted','接受为候选'],['rejected','驳回']],'accepted')}${select('motion','实际呈现的运动',Object.entries(motionNames),x.motion)}${area('note','检查结果与原因','','required')}`,'review',`data-id="${id}"`);return;}
 if(a==='select-asset'){modal('把候选关联到分镜',select('shot_id','镜头',c.shots.map(s=>[s.id,s.id+' · '+s.action.slice(0,25)]),c.shots[0]?.id)+select('track','用途',[['visual','选为主画面'],['audio','选为旁白音轨'],['reference','加入参考图']],'visual'),'select-asset',`data-id="${id}"`);return;}
 if(a==='inspect-result'){const t=S.tasks.find(t=>t.id===id);modal('审阅生成结果',`<p class="small">${t.result.mock?'MOCK 结构模板，需自行编写完善。':'模型产物仍需审阅。'} 来源版本 v${t.revision}；当前 v${S.project.revision}。</p>`+area('result','候选内容（只读；应用后可编辑）',JSON.stringify(t.result.data,null,2),'class="json-editor" readonly'),'apply',`data-id="${id}"`);return;}
 if(a==='cancel-task'){await api(base()+`/tasks/${id}/cancel`,{method:'POST'});await refresh();toast('已请求取消。远端可能仍运行；不会假设自动退款。');return;}
 if(a==='reconcile'){await api(base()+`/tasks/${id}/reconcile`,{method:'POST'});await refresh();return;}
 if(a==='approve'){const g=el.dataset.gate;modal('人工确认 · '+g,`<p class="small">绑定当前 v${S.project.revision}。G3/G4 不能使用 MOCK，必须看过相邻动作样片或完整成片。</p>${['G3','G4'].includes(g)?select('task_id','被审核的渲染任务',S.tasks.filter(t=>t.kind==='render'&&t.state==='succeeded'&&!t.result.mock).map(t=>[t.id,t.id.slice(0,10)+' · '+t.result.qa.duration_seconds+' 秒']),null)+`<div class="checklist">${[['identity','人物一致'],['motion','动作完整'],['continuity','衔接自然'],['voice','声音正确'],['subtitles','字幕可读']].map(([k,t])=>`<label><input type="checkbox" name="check" value="${k}" required>${t}</label>`).join('')}</div>`:''}${area('note','人工审核结论','','required')}`,'approve',`data-gate="${g}"`);return;}
 if(a==='budget'){modal('授权本项目预算',`<div class="field-row three">${select('currency','币种',[['USD','USD'],['CNY','CNY']],'USD')}${field('limit','总上限','10')}${field('per','单次上限','1')}</div>${field('providers','允许供应商 ID（逗号分隔）',(S.settings.providers||[]).map(p=>p.id).join(','))}${field('kinds','允许任务类型（逗号分隔）','concepts,script,bible,storyboard,image,video,tts')}${field('hours','有效小时',24,'number','min="1" max="720"')}<label><input name="outbound" type="checkbox">允许向所选供应商外发本项目明确引用的参考图</label><p class="small">预占是本地准入约束，不是供应商价格保证。实际费用以账单核对，未知费用继续占用额度。</p>`,'budget');return;}
 if(a==='revoke'){await api(base()+`/budgets/${id}/revoke`,{method:'POST'});await refresh();return;}
 if(a==='settle'){modal('按实际账单登记费用',field('amount','实际费用（预算币种）','0')+area('evidence','账单编号 / 核对依据','','required'),'settle',`data-id="${id}"`);return;}
 if(a==='audio-track'){modal('添加连续声音轨',select('asset_id','已审核音频',S.assets.filter(a=>a.kind==='audio'&&a.review==='accepted').map(a=>[a.id,a.name]),null)+`<div class="field-row three">${field('start','时间线开始（秒）',0,'number','min="0" step="0.001"')}${field('source','素材入点（秒）',0,'number','min="0" step="0.001"')}${field('duration','使用时长（秒）',1,'number','min="0.001" step="0.001"')}</div><div class="field-row">${select('bus','轨道类型',[['music','音乐'],['speech','连续旁白'],['sfx','音效']],'music')}${field('gain','音量增益',0.3,'number','min="0" max="4" step="0.05"')}</div>`,'audio');return;}
 if(a==='restore'){if(confirm('将此历史版本恢复为一个新版本？')){S.project=await api(base()+'/restore/'+el.dataset.number,{method:'POST',body:{expected_revision:S.project.revision}});render();}return;}
 if(a==='export'){const blob=await api(base()+`/tasks/${id}/export`,{method:'POST',blob:true});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='mj-project.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
 if(a==='demo-project'){await demoProject();return;}
}
const split=s=>String(s||'').split(/[,，]/).map(s=>s.trim()).filter(Boolean);
async function submit(form){const f=new FormData(form),v=Object.fromEntries(f),type=form.dataset.form,c=S.project?clone(S.project.content):null;
 if(type==='login'){const r=await api('/login',{method:'POST',body:v});S.csrf=r.csrf;S.settings=await api('/settings');S.projects=await api('/projects');S.page='home';render();return;}
 if(type==='project'){const small=v.size==='preview',width=v.aspect==='portrait'?(small?360:1080):(small?640:1920),height=v.aspect==='portrait'?(small?640:1920):(small?360:1080);S.project=await api('/projects',{method:'POST',body:{title:v.title,brief:v.brief,style:v.style,spec:{width,height,fps:30,total_frames:Math.round(Number(v.duration)*30)}}});close();await loadProject(S.project.id);S.projects=await api('/projects');S.page='overview';render();return;}
 if(type==='story'){c.selected_concept=v.selected||'';c.concepts.forEach((x,i)=>['title','logline','conflict','ending'].forEach(k=>x[k]=v[k+'_'+i]));c.script.forEach((b,i)=>{b.action=v['action_'+i];b.narration=v['narration_'+i];b.speaker_id=v['speaker_'+i];b.emotion=v['emotion_'+i];});await saveContent(c);return;}
 if(type==='bible'){for(const k of ['characters','scenes','props'])c.bible[k].forEach((x,i)=>{x.name=v[k+'_name_'+i];x.description=v[k+'_description_'+i];x.reference_ids=split(v[k+'_refs_'+i]);});await saveContent(c);return;}
 if(type==='json'){await saveContent(JSON.parse(v.json));close();return;}
 if(type==='shot'){const old=c.shots.find(s=>s.id===form.dataset.original),s={...(old||{}),id:v.id,frames:+v.frames,framing:v.framing,scene_id:v.scene_id,beat_id:v.beat_id,character_ids:split(v.characters),action:v.action,before:v.before,after:v.after,motion:v.motion,narration:v.narration,reference_ids:split(v.refs),source_in_frames:+v.source_in_frames,fit:v.fit};if(old)c.shots[c.shots.indexOf(old)]=s;else c.shots.push(s);await saveContent(c);close();return;}
 if(type==='generate'){const kind=form.dataset.kind;const body={kind,provider:v.provider||'mock',shot_id:v.shot_id||form.dataset.shot||'',expected_revision:S.project.revision,prompt:v.prompt||'',cap_micros:micros(v.cap||'0'),budget_id:v.budget_id||null,dry_run:!!v.dry,sample:!!v.sample,sample_shot_ids:split(v.sample_ids),voice:v.voice||'alloy'};const provider=(S.settings.providers||[]).find(p=>p.id===body.provider);if(provider?.type==='comfyui'){body.cap_micros=0;body.budget_id=null;body.reference_ids=f.getAll('comfy_ref').filter(Boolean);body.image_options={workflow:v.comfy_workflow||provider.default_workflow,seed:v.comfy_seed===''?null:Number(v.comfy_seed),width:+v.comfy_width,height:+v.comfy_height,negative_prompt:v.comfy_negative||'',mask_asset_id:v.comfy_mask||null,denoise:v.comfy_denoise?Number(v.comfy_denoise):null,allow_remote_processing:!!v.comfy_consent,use_shot_references:false};if(v.comfy_seed!==''&&!Number.isSafeInteger(body.image_options.seed))throw new Error('种子须为 JavaScript 安全整数，或留空由服务端生成');if(!body.dry_run&&!body.image_options.allow_remote_processing)throw new Error('请明确勾选远程处理授权');}else if(body.provider!=='mock'&&!body.dry_run&&!confirm('确认使用已授权预算向外部供应商提交？'))return;const t=await api(base()+'/tasks',{method:'POST',body});close();if(t.dry_run){toast(JSON.stringify(t.quote,null,2));return;}S.page='tasks';await refresh();toast('任务已入队。请保持 Worker 运行；关闭页面不会丢失任务。');return;}
 if(type==='upload'){await api(base()+'/assets',{method:'POST',body:f});close();await refresh();toast('素材已验证并保存，尚未自动选用。');return;}
 if(type==='review'){await api(base()+`/assets/${form.dataset.id}/review`,{method:'POST',body:v});close();await refresh();return;}
 if(type==='select-asset'){S.project=await api(base()+`/assets/${form.dataset.id}/select`,{method:'POST',body:{...v,expected_revision:S.project.revision}});close();render();return;}
 if(type==='apply'){S.project=await api(base()+`/tasks/${form.dataset.id}/apply`,{method:'POST',body:{expected_revision:S.project.revision}});close();S.page='story';await refresh();return;}
 if(type==='approve'){await api(base()+'/approvals',{method:'POST',body:{gate:form.dataset.gate,expected_revision:S.project.revision,task_id:v.task_id||null,note:v.note,checks:f.getAll('check')}});close();await refresh();return;}
 if(type==='budget'){await api(base()+'/budgets',{method:'POST',body:{currency:v.currency,limit_micros:micros(v.limit),per_task_micros:micros(v.per),providers:split(v.providers),kinds:split(v.kinds),expires_in_hours:+v.hours,allow_reference_upload:!!v.outbound}});close();await refresh();return;}
 if(type==='settle'){await api(base()+`/tasks/${form.dataset.id}/settle`,{method:'POST',body:{amount_micros:micros(v.amount),evidence:v.evidence}});close();await refresh();return;}
 if(type==='subtitle'){c.subtitles={font_size:+v.font_size,margin_v:+v.margin_v,line_chars:+v.line_chars};c.duck_music=!!v.duck;await saveContent(c);return;}
 if(type==='audio'){c.extra_audio.push({asset_id:v.asset_id,start_sample:Math.round(+v.start*48000),source_in_sample:Math.round(+v.source*48000),samples:Math.round(+v.duration*48000),gain:+v.gain,bus:v.bus,fade_samples:v.bus==='music'?24000:0});await saveContent(c);close();return;}
}
async function demoProject(){
 const p=await api('/projects',{method:'POST',body:{title:'借来的光 · 离线工程演示',brief:'雨夜修理铺停电，年轻学徒在老修理师帮助下修亮旧灯，最后把这束光留在门口。此项目只验证软件流程。',style:'工程预演，所有占位画面明确标注 MOCK',spec:{width:360,height:640,fps:30,total_frames:3600}}});S.project=p;
 const c=clone(p.content);c.concepts=[{id:'CPT1',title:'借来的光',logline:p.brief,conflict:'停电与不被信任的旧灯',ending:'修亮旧灯并挂在门口'},{id:'CPT2',title:'雨停之前',logline:'从门外的视角观察修理铺',conflict:'年轻人不愿等待',ending:'他选择留下帮忙'},{id:'CPT3',title:'留一盏灯',logline:'先看到亮灯，再回溯修灯过程',conflict:'旧物与新物的价值冲突',ending:'光照亮台阶'}];c.selected_concept='CPT1';
 const actions=['灯突然熄灭，阿澄抬头。','阿澄取出手机，发现电量不足。','雨水淹过门口台阶。','林伯从抽屉取出旧灯。','阿澄按开关，灯闪烁后熄灭。','林伯指向旧灯的背盖。','阿澄打开背盖，观察触点。','阿澄用布清洁触点。','林伯扶稳灯身，阿澄合上背盖。','阿澄按下开关，暖光稳定亮起。','两人提灯走向门口。','灯光照亮积水下的台阶。','阿澄把灯挂在门边。','暖光与雨水映在台阶上。','手机关机，阿澄看向旧灯。','林伯递给阿澄一块干布。','阿澄把灯稍稍转向门外。','两人站在门口听雨。','旧灯背面写着：留给需要的人。','镜头拉远，门前仍有稳定灯光。'];
 c.script=actions.map((action,i)=>({id:'B'+String(i+1).padStart(2,'0'),action,narration:'',speaker_id:'narrator',emotion:'克制、温暖'}));c.bible={characters:[{id:'C01',name:'阿澄',description:'短黑发，蓝色外套，黄色胸标',reference_ids:[]},{id:'C02',name:'林伯',description:'灰白短发，圆框眼镜，棕色围裙',reference_ids:[]}],scenes:[{id:'SC01',name:'旧修理铺',description:'木桌居中，门在右侧，雨夜停电',reference_ids:[]}],props:[{id:'P01',name:'旧手提灯',description:'开盖、清洁、合盖、亮起、悬挂依次衔接',reference_ids:[]}]};
 c.shots=actions.map((action,i)=>({id:'SH'+String(i+1).padStart(2,'0'),beat_id:c.script[i].id,scene_id:'SC01',character_ids:['C01','C02'],frames:180,action,motion:'subject_action',before:'根据上一镜头核对',after:'为下一动作保留承接',framing:'中景',narration:'',reference_ids:[]}));
 S.project=await api(base()+'/workspace',{method:'PUT',body:{expected_revision:p.revision,content:c}});await loadProject(p.id);S.projects=await api('/projects');S.page='story';render();toast('工程示例已创建。可以编辑分镜并制作完整预演；它不是已生成的漫剧。');
}
function comfyFields(form,keep=false){
 const panel=form.querySelector('#comfy-options');if(!panel)return;
 const provider=(S.settings.providers||[]).find(p=>p.id===form.elements.provider?.value);
 const isComfy=provider?.type==='comfyui';
 for(const name of ['budget_id','cap']){const input=form.elements[name];if(input){input.disabled=isComfy;input.closest('label').hidden=isComfy;}}
 if(!isComfy){panel.innerHTML='';return;}
 const wid=keep?form.elements.comfy_workflow?.value:provider.default_workflow;
 const w=provider.workflows.find(x=>x.id===wid)||provider.workflows[0];
 const selected=keep?[...form.querySelectorAll('[name=comfy_ref]')].map(x=>x.value):[];
 const images=S.assets.filter(a=>a.kind==='image'&&!a.mock&&a.review==='accepted');
 const choices=[['','请选择已审核图片'],...images.map(a=>[a.id,a.name+' · '+a.id.slice(0,8)])];
 panel.innerHTML=`<div class="banner warn">自托管 GPU 生图：只生成候选，不会自动选用。下面的顺序就是本次参考顺序，不自动追加镜头引用。SDXL 基础改图不承诺锁脸。</div>${select('comfy_workflow','工作流（服务端已固定版本）',provider.workflows.map(w=>[w.id,w.title]),w.id)}<p class="small">模式：${esc(w.mode)} · 参考图 ${w.references} 张 · 工作流 ${esc(w.sha256.slice(0,12))}</p>${Array.from({length:w.references},(_,i)=>select('comfy_ref','参考图 '+(i+1),choices,selected[i]||'')).join('')}${w.mode==='inpaint'?select('comfy_mask','蒙版（白色重绘、黑色保留；原尺寸须与参考图1一致）',choices,''):''}<div class="field-row">${field('comfy_width','图片宽度',provider.default_size[0],'number','step="8" min="256" max="2048"')}${field('comfy_height','图片高度',provider.default_size[1],'number','step="8" min="256" max="2048"')}</div>${field('comfy_seed','随机种子（留空自动固定）','','number','min="0" max="9007199254740991"')}${area('comfy_negative','负面提示词（可留空）','')}${w.mode!=='text'?field('comfy_denoise','改图强度 0.01–1（留空用模板值）','','number','min="0.01" max="1" step="0.01"'):''}<label><input type="checkbox" name="comfy_consent">我允许把本次提示词、参考图和蒙版发送到管理员配置的 GPU 服务器，并使用其计算资源。</label>`;
}
document.addEventListener('change',e=>{const f=e.target.closest('form[data-form="generate"]');if(f&&['provider','comfy_workflow'].includes(e.target.name))comfyFields(f,e.target.name==='comfy_workflow');});
document.addEventListener('click',async e=>{const el=e.target.closest('button[data-act]');if(!el||!el.dataset.act)return;e.preventDefault();if(el.disabled)return;el.disabled=true;try{await action(el);}catch(err){toast(err.message,true);}finally{el.disabled=false;}});
document.addEventListener('submit',async e=>{const f=e.target;if(!f.matches('form[data-form]'))return;e.preventDefault();const b=f.querySelector('button[type=submit]');if(b?.disabled)return;if(b)b.disabled=true;try{await submit(f);}catch(err){toast(err.message,true);}finally{if(b)b.disabled=false;}});
setInterval(async()=>{if(S.page==='tasks'&&S.project&&!$('#modal').open){try{S.tasks=await api(base()+'/tasks');render();}catch{}}},5000);
try{const session=await api('/session');S.csrf=session.csrf;[S.settings,S.projects]=await Promise.all([api('/settings'),api('/projects')]);render();}catch{loginScreen();}
